# Generated by Django 4.2.4 on 2023-08-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_alter_customeruser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='dog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authe.customerdog'),
        ),
    ]
