# Generated by Django 4.2.4 on 2023-08-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_search_vector_alter_brand_description_and_more'),
        ('authe', '0004_alter_possibleallergies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='all_carts_inside', to='shop.product', verbose_name='Users Cart'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='dog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs_user', to='authe.customerdog'),
        ),
    ]
