# Generated by Django 4.2.4 on 2023-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0007_customeruser_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='limit_ajax_email_validators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('banned', models.DateTimeField()),
                ('request_amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
