# Generated by Django 4.2.4 on 2023-09-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0008_limit_ajax_email_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit_ajax_email_validators',
            name='banned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limit_ajax_email_validators',
            name='request_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
