# Generated by Django 4.2.4 on 2023-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0010_customeruser_email_for_verification_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdog',
            old_name='male',
            new_name='is_male',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='email_for_verification_needed',
        ),
        migrations.AddField(
            model_name='possibleallergies',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
