# Generated by Django 4.2.4 on 2023-09-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0011_rename_male_customerdog_is_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='dog',
        ),
        migrations.AddField(
            model_name='customerdog',
            name='human',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dog', to=settings.AUTH_USER_MODEL, verbose_name="dog's human"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='allergy',
            field=models.ManyToManyField(blank=True, to='authe.possibleallergies'),
        ),
    ]
