# Generated by Django 4.2.4 on 2023-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0012_remove_customeruser_dog_customerdog_human_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('user_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unverified User',
                'verbose_name_plural': 'Unverified Users',
            },
        ),
        migrations.AlterModelOptions(
            name='customercart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='verification_token_expiry',
        ),
    ]
