# Generated by Django 4.2.4 on 2023-09-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0014_rename_allergy_customerdog_allergys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleallergies',
            name='_allergic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possibleallergies',
            name='_dog_name',
            field=models.CharField(null=True),
        ),
    ]
