# Generated by Django 4.2.4 on 2023-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0016_rename__allergic_possibleallergies_allergic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleallergies',
            options={'ordering': ['-allergic', 'name']},
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='allergys',
            field=models.ManyToManyField(blank=True, related_name='dog_allergies', to='authe.possibleallergies'),
        ),
        migrations.AlterField(
            model_name='possibleallergies',
            name='allergic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='possibleallergies',
            name='dog_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
