# Generated by Django 4.2.4 on 2023-09-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0017_alter_possibleallergies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleallergies',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='possibleallergies',
            name='allergic',
        ),
        migrations.RemoveField(
            model_name='possibleallergies',
            name='dog_name',
        ),
    ]
