# Generated by Django 4.2.4 on 2023-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0018_alter_possibleallergies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
