# Generated by Django 4.2.4 on 2023-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0019_unverifieduser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleallergies',
            name='allergic',
            field=models.BooleanField(null=True),
        ),
    ]
