# Generated by Django 4.2.4 on 2023-09-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0021_remove_possibleallergies_allergic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdog',
            name='dog_number',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
