# Generated by Django 4.2.4 on 2023-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0023_possiblebreeds_alter_customerdog_dog_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleallergies',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='possiblebreeds',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='allergys',
            field=models.ManyToManyField(blank=True, null=True, related_name='dog_allergies', to='authe.possibleallergies'),
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='breed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dogs Breed'),
        ),
    ]
