# Generated by Django 4.2.4 on 2023-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0024_alter_possibleallergies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdog',
            name='allergys',
            field=models.ManyToManyField(blank=True, null=True, to='authe.possibleallergies'),
        ),
        migrations.RemoveField(
            model_name='customerdog',
            name='breed',
        ),
        migrations.AddField(
            model_name='customerdog',
            name='breed',
            field=models.ManyToManyField(blank=True, null=True, to='authe.possiblebreeds', verbose_name='Dogs Breed'),
        ),
    ]
