# Generated by Django 4.2.4 on 2023-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0025_alter_customerdog_allergys_remove_customerdog_breed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleallergies',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='possiblebreeds',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='allergys',
            field=models.ManyToManyField(blank=True, to='authe.possibleallergies'),
        ),
        migrations.AlterField(
            model_name='customerdog',
            name='breed',
            field=models.ManyToManyField(blank=True, to='authe.possiblebreeds', verbose_name='Dogs Breed'),
        ),
    ]
