#doesnt work

from .models import PossibleAllergies

#change the list than runscript using python manage.py runscript script_name
allergy_choices = [
        "Beef",
        "Chicken",
        "Dairy(milk, cheese)",
        "Eggs",
        "Wheat",
        "Soy",
        "Corn",
        "Fish",
        "Lamb",
        "Pork",
        "Turkey",
        "Rabbit",
        "Venison",
        "Duck",
        "Potato",
        "Sweet potatoes",
        "Rice",
        "Barley",
        "Oats",
        "Rye",
        "Peanuts",
        "Tree nuts(almonds, walnuts)",
        "Sunflower seeds",
        "Flaxseeds",
        "Sesame seeds",
        "Coconut",
        "Lentils",
        "Chickpeas",
        "Kidney beans",
        "Green peas",
        "Tomatoes",
        "Carrots",
        "Spinach",
        "Broccoli",
        "Cauliflower",
        "Bell peppers",
        "Apples",
        "Bananas",
        "Blueberries",
        "Strawberries",
        "Pineapple",
        "Watermelon",
        "Grapes",
        "Raisins",
        "Oranges",
        "Lemons",
        "Lime",
        "Mango",
        "Papaya",
        "Kiwi",
        "Cranberries",
        "Cinnamon",
        "Nutmeg",
        "Garlic",
        "Onions",
        "Chives",
        "Mushrooms",
        "Avocado",
        "Peaches",
        "Plums",
        "Cherries",
        "Apricots",
        "Prunes",
        "Pomegranates",
        "Pears",
        "Melon",
        "Quinoa",
        "Millet",
        "Spelt",
        "Teff",
        "Sorghum",
        "Tapioca",
        "Buckwheat",
        "Alfalfa",
        "Spirulina",
        "Chia seeds",
        "Crab",
        "Lobster",
        "Shrimp",
        "Clams",
        "Mussels",
        "Scallops",
        "Sardines",
        "Anchovies",
        "Herring",
        "Trout",
        "Salmon",
        "Tuna",
        "Cod",
        "Pollock",
        "Catfish",
        "Bass",
        "Perch",
        "Tilapia",
        "Mackerel",
        "Flounder",
        "Whitefish",
        "Halibut",
        "Sole",
        "Mahi-mahi",
    ]
all_obj = PossibleAllergies.objects.all()
for allergy_model in all_obj:
    if not allergy_model.name in allergy_model:
        allergy_model.delete()
for allergy in allergy_choices:
    if not allergy in all_obj:
        add_allergy = PossibleAllergies(name=allergy)
        add_allergy.save()