# Generated by Django 4.2.4 on 2023-08-24 08:06

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6, validators=[shop.models.is_hexadecimal])),
            ],
        ),
        migrations.CreateModel(
            name='productIngrediants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=30)),
                ('Dimensionx', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Dimensiony', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Dimensionz', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('To', 'Toys'), ('Tr', 'Treats'), ('MC', 'Monthly Crates')], max_length=2)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[shop.models.validate_positve], verbose_name='Product Price')),
                ('ship_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[shop.models.validate_positve], verbose_name='Shipping Cost')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Available')),
                ('images', models.ImageField(upload_to='images/')),
                ('about_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.aboutproduct')),
                ('ingrediants', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.productingrediants')),
            ],
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='colors',
            field=models.ManyToManyField(to='shop.colors'),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='sizes',
            field=models.ManyToManyField(to='shop.sizes'),
        ),
    ]
