# Generated by Django 4.2.4 on 2023-08-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_customeruser_dog'),
        ('shop', '0002_rename_productingrediants_productingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.ManyToManyField(to='authe.possibleallergies'),
        ),
        migrations.DeleteModel(
            name='productIngredients',
        ),
    ]
