# Generated by Django 4.2.4 on 2023-08-25 07:46

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproduct',
            name='Weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product Weight in grams'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[shop.models.is_hexadecimal]),
        ),
        migrations.AlterField(
            model_name='colors',
            name='color_name',
            field=models.CharField(blank=True, default='default', max_length=30),
        ),
    ]
