# Generated by Django 4.2.4 on 2023-08-25 08:47

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_sizes_dimensionx_alter_sizes_dimensiony_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproduct',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='aboutproduct',
            name='sizes',
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='Dimensionx',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='Dimensiony',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='Dimensionz',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[shop.models.is_hexadecimal]),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='color_name',
            field=models.CharField(blank=True, default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='size_name',
            field=models.CharField(blank=True, default='default', max_length=30),
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
