# Generated by Django 4.2.4 on 2023-08-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_aboutproduct_colors_remove_aboutproduct_sizes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Dimensionx',
            new_name='Dimension_x',
        ),
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Dimensiony',
            new_name='Dimension_y',
        ),
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Dimensionz',
            new_name='Dimension_z',
        ),
    ]
