# Generated by Django 4.2.4 on 2023-08-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_dimensionx_aboutproduct_dimension_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Dimension_x',
            new_name='dimension_x',
        ),
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Dimension_y',
            new_name='dimension_y',
        ),
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Dimension_z',
            new_name='dimension_z',
        ),
    ]
