# Generated by Django 4.2.4 on 2023-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_dimension_x_aboutproduct_dimension_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_code',
            field=models.CharField(choices=[('Fo', 'Food'), ('To', 'Toys'), ('Tr', 'Treats'), ('MC', 'Monthly Crates')], max_length=2),
        ),
    ]
