# Generated by Django 4.2.4 on 2023-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_alter_possibleallergies_name'),
        ('shop', '0012_alter_product_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ingredients',
            field=models.ManyToManyField(blank=True, to='authe.possibleallergies'),
        ),
    ]
