# Generated by Django 4.2.4 on 2023-08-27 10:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_search_vector_alter_brand_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(height_field='height', upload_to='product/images/', width_field='width'), null=True, size=8),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
