# Generated by Django 4.2.4 on 2023-08-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_image_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_code',
            new_name='typeee_code',
        ),
    ]
