# Generated by Django 4.2.4 on 2023-08-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_type_code_product_typeee_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='typeee_code',
            new_name='type_code',
        ),
    ]
