# Generated by Django 4.2.4 on 2023-09-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.aboutproduct'),
        ),
    ]
