# Generated by Django 4.2.4 on 2023-09-01 06:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_product_about_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproduct',
            name='dimension_x',
        ),
        migrations.RemoveField(
            model_name='aboutproduct',
            name='dimension_y',
        ),
        migrations.RemoveField(
            model_name='aboutproduct',
            name='dimension_z',
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='dimension',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=12), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='aboutproduct',
            name='size_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_product',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.aboutproduct'),
        ),
    ]
