# Generated by Django 4.2.4 on 2023-09-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_about_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about_product',
        ),
    ]
