# Generated by Django 4.2.4 on 2023-09-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_aboutproduct_dimension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutproduct',
            old_name='Weight',
            new_name='weight',
        ),
    ]
