# Generated by Django 4.2.4 on 2023-09-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_rename_weight_aboutproduct_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
