# Generated by Django 4.2.4 on 2023-09-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_product_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dog_allergic_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
