# Generated by Django 4.2.4 on 2023-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_dog_allergic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dog_allergic_name',
        ),
    ]
