# Generated by Django 4.2.4 on 2023-09-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_product_dog_allergic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='shop.brand', verbose_name="Product's brand"),
        ),
    ]
