# Generated by Django 4.2.4 on 2023-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='descaled_image',
            field=models.ImageField(auto_created=True, default='a', editable=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
